package praservidorarquivo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;
import javax.swing.text.html.HTMLDocument;
import javax.swing.text.html.HTMLEditorKit;

/**
 * <h1>Janela Servidor</h1>
 * Classe que irá criar a interface gráfica do servidor.
 * No momento, é apenas um console.
 *
 * @author Adriano
 * @author Gustavo
 */
public class JanelaServidor extends javax.swing.JFrame {

    /**
     * Váriavel utilizada para processar texto em HTML
     */
    private HTMLEditorKit edKit;

    /**
     * Unica instância do {@link JanelaServidor}
     */
    private static JanelaServidor self = null;

    /**
     * Retorna a instancia do {@link JanelaServidor}
     *
     * @return instancia da classe
     */
    public static JanelaServidor getInstance () {
        if ( self == null ) {
            self = new JanelaServidor ();
        }
        return self;
    }

    /**
     * Construtor da classe que inicia os componentes da interface gráfica e
     * aloca algumas variáveis.
     */
    private JanelaServidor () {
        initComponents ();
        this.setVisible ( true );
        edKit = new HTMLEditorKit ();
        painel_texto.setEditorKit ( edKit );
        painel_texto.setDocument ( new HTMLDocument () );
    }

    /**
     * Adiciona uma mensagem de log no console
     *
     * @param msg      mensagem a ser adiconada
     * @param clientId id do cliente que criou a mensagem
     */
    public void AddMensagemLog ( String msg, int clientId ) {
        try {
            edKit.insertHTML ( ( HTMLDocument ) painel_texto.getDocument (),
                    painel_texto.getDocument ().getLength (),
                    "<div>" + "<font size=3 color=#000000>" + ( clientId == -1 ? "Servidor:" : clientId ) + "</font><font color=#ff00000>-> </font>" + msg + "</div>",
                    0,
                    0,
                    null );
        }
        catch ( BadLocationException | IOException ex ) {
            Logger.getLogger ( JanelaServidor.class.getName () ).log ( Level.SEVERE, null, ex );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painel_texto = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(painel_texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane painel_texto;
    // End of variables declaration//GEN-END:variables
}
