/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FreeClientePackage;

/**
 *
 * @author adrianozj
 */
public class InterfaceFreeCliente extends javax.swing.JFrame {
    
    private static final String SEPARADOR = ":";
    
    private static InterfaceFreeCliente instance;
    
    /**
     *
     * @return
     */
    public static InterfaceFreeCliente getInstance(){
        if (instance == null){
            instance = new InterfaceFreeCliente();
        }
        return instance;
    }

    /**
     * Creates new form InterfaceFreeCliente
     */
    private InterfaceFreeCliente() {
        initComponents();
        showUsername.setText(FreeCliente.getInstance().getUsername());
        mudouOTurno( FreeCliente.getInstance().getTurn(), FreeCliente.getInstance().getPlayerTurn());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butt11 = new javax.swing.JToggleButton();
        butt12 = new javax.swing.JToggleButton();
        butt13 = new javax.swing.JToggleButton();
        butt23 = new javax.swing.JToggleButton();
        butt22 = new javax.swing.JToggleButton();
        butt21 = new javax.swing.JToggleButton();
        butt33 = new javax.swing.JToggleButton();
        butt32 = new javax.swing.JToggleButton();
        butt31 = new javax.swing.JToggleButton();
        painelStatus = new javax.swing.JPanel();
        gameStatus = new javax.swing.JLabel();
        playStatus = new javax.swing.JLabel();
        buttLeave = new javax.swing.JButton();
        buttGiveUp = new javax.swing.JButton();
        painelNomeUsuario = new javax.swing.JPanel();
        showUsername = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        showEnemyname = new javax.swing.JLabel();
        vsText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butt11.setText("1/1");
        butt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt11ActionPerformed(evt);
            }
        });

        butt12.setText("1/2");
        butt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt12ActionPerformed(evt);
            }
        });

        butt13.setText("1/3");
        butt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt13ActionPerformed(evt);
            }
        });

        butt23.setText("2/3");
        butt23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt23ActionPerformed(evt);
            }
        });

        butt22.setText("2/2");
        butt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt22ActionPerformed(evt);
            }
        });

        butt21.setText("2/1");
        butt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt21ActionPerformed(evt);
            }
        });

        butt33.setText("3/3");
        butt33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt33ActionPerformed(evt);
            }
        });

        butt32.setText("3/2");
        butt32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt32ActionPerformed(evt);
            }
        });

        butt31.setText("3/1");
        butt31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt31ActionPerformed(evt);
            }
        });

        painelStatus.setBackground(new java.awt.Color(255, 255, 255));
        painelStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gameStatus.setText("Game status...");

        playStatus.setText("Play status...");

        javax.swing.GroupLayout painelStatusLayout = new javax.swing.GroupLayout(painelStatus);
        painelStatus.setLayout(painelStatusLayout);
        painelStatusLayout.setHorizontalGroup(
            painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelStatusLayout.createSequentialGroup()
                .addGroup(painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameStatus)
                    .addComponent(playStatus))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelStatusLayout.setVerticalGroup(
            painelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelStatusLayout.createSequentialGroup()
                .addComponent(gameStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playStatus))
        );

        buttLeave.setText("Sair");
        buttLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttLeaveActionPerformed(evt);
            }
        });

        buttGiveUp.setText("Desistir");
        buttGiveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttGiveUpActionPerformed(evt);
            }
        });

        painelNomeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        painelNomeUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        showUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showUsername.setText("Username");

        javax.swing.GroupLayout painelNomeUsuarioLayout = new javax.swing.GroupLayout(painelNomeUsuario);
        painelNomeUsuario.setLayout(painelNomeUsuarioLayout);
        painelNomeUsuarioLayout.setHorizontalGroup(
            painelNomeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomeUsuarioLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(showUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelNomeUsuarioLayout.setVerticalGroup(
            painelNomeUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNomeUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showUsername)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        showEnemyname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showEnemyname.setText("Enemyname");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(showEnemyname)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showEnemyname)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vsText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vsText.setText("VS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttGiveUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttLeave))
                            .addComponent(painelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(vsText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butt11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butt12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butt13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butt22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butt23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butt21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(butt31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butt32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(butt33)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vsText)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt11)
                    .addComponent(butt12)
                    .addComponent(butt13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butt21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butt23)
                        .addComponent(butt22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt33)
                    .addComponent(butt32)
                    .addComponent(butt31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttLeave)
                    .addComponent(buttGiveUp))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt11ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(1, 1);
    }//GEN-LAST:event_butt11ActionPerformed

    private void butt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt12ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(1, 2);
    }//GEN-LAST:event_butt12ActionPerformed

    private void butt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt13ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(1, 3);
    }//GEN-LAST:event_butt13ActionPerformed

    private void butt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt21ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(2,1);
    }//GEN-LAST:event_butt21ActionPerformed

    private void butt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt22ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(2,2);
    }//GEN-LAST:event_butt22ActionPerformed

    private void butt23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt23ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(2,3);
    }//GEN-LAST:event_butt23ActionPerformed

    private void butt31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt31ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(3,1);
    }//GEN-LAST:event_butt31ActionPerformed

    private void butt32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt32ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(3,2);
    }//GEN-LAST:event_butt32ActionPerformed

    private void butt33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt33ActionPerformed
        // TODO add your handling code here:
        if(FreeCliente.getInstance().ifMyTurn())
            FreeCliente.getInstance().fixChoice(3,3);
    }//GEN-LAST:event_butt33ActionPerformed

    private void buttLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttLeaveActionPerformed
        // TODO add your handling code here:
        FreeCliente.getInstance().leave();
        dispose();
    }//GEN-LAST:event_buttLeaveActionPerformed

    private void buttGiveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttGiveUpActionPerformed
        // TODO add your handling code here:
        FreeCliente.getInstance().giveUp();
        
    }//GEN-LAST:event_buttGiveUpActionPerformed
    
    /**
     *
     * @param turn
     * @param playerTurn
     */
    public final void mudouOTurno(short turn, short playerTurn) {
        if( turn == playerTurn)
            gameStatus.setText("Seu turno.");
        else if( turn == 0)
            gameStatus.setText("Procurando oponente...");
        else
            gameStatus.setText("Turno do oponente.");
    }
    
    public void refreshGame( String message){
        String campos[] = message.split(SEPARADOR);
        butt11.setText(campos[0]);
        butt12.setText(campos[1]);
        butt13.setText(campos[2]);
        butt21.setText(campos[3]);
        butt22.setText(campos[4]);
        butt23.setText(campos[5]);
        butt31.setText(campos[6]);
        butt32.setText(campos[7]);
        butt33.setText(campos[8]);
    }
    
    public void setThisScrean(boolean state){
        setVisible(state);
    }
    
    public void setPlayStatus(String message){
        playStatus.setText(message);
    }
    
    public void setEnemyName(String enemyName){
        showEnemyname.setText( enemyName);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton butt11;
    private javax.swing.JToggleButton butt12;
    private javax.swing.JToggleButton butt13;
    private javax.swing.JToggleButton butt21;
    private javax.swing.JToggleButton butt22;
    private javax.swing.JToggleButton butt23;
    private javax.swing.JToggleButton butt31;
    private javax.swing.JToggleButton butt32;
    private javax.swing.JToggleButton butt33;
    private javax.swing.JButton buttGiveUp;
    private javax.swing.JButton buttLeave;
    private javax.swing.JLabel gameStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelNomeUsuario;
    private javax.swing.JPanel painelStatus;
    private javax.swing.JLabel playStatus;
    private javax.swing.JLabel showEnemyname;
    private javax.swing.JLabel showUsername;
    private javax.swing.JLabel vsText;
    // End of variables declaration//GEN-END:variables

}
