/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente_pra;

import javax.swing.JOptionPane;

/**
 *
 * @author Adriano Zanella Junior
 * @author Gustavo Diel
 */
public class ClienteFramer extends javax.swing.JFrame {
    
    private static ClienteFramer instance;
    
    public static ClienteFramer getInstance(){
        if (instance == null){
            instance = new ClienteFramer ();
        }
        return instance;
    }

    /**
     * Creates new form ClienteFramer
     */
    private ClienteFramer () {
        initComponents ();
        ipServer.setText ( Cliente.getInstance ().getIpServer () );
        setLocationRelativeTo ( null );
    }
    
    public void fecha(){
        dispose();
        instance = null;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( {"unchecked", "Convert2Lambda"} )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttEditar = new javax.swing.JButton();
        ipServer = new javax.swing.JLabel();
        buttDesconectar = new javax.swing.JButton();
        buttProcurar = new javax.swing.JButton();
        buttDeletar = new javax.swing.JButton();
        buttInserir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttEditar.setText("Editar");
        buttEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttEditarActionPerformed(evt);
            }
        });

        ipServer.setText("IpServer");

        buttDesconectar.setText("Desconectar");
        buttDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDesconectarActionPerformed(evt);
            }
        });

        buttProcurar.setText("Procurar");
        buttProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttProcurarActionPerformed(evt);
            }
        });

        buttDeletar.setText("Deletar");
        buttDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDeletarActionPerformed(evt);
            }
        });

        buttInserir.setText("Inserir");
        buttInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttProcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttEditar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttDesconectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addComponent(ipServer))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttEditar)
                    .addComponent(buttProcurar)
                    .addComponent(buttDeletar)
                    .addComponent(buttInserir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ipServer))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttDesconectar)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttEditarActionPerformed
        // TODO add your handling code here:
        String msg = JOptionPane.showInputDialog ( this, "Por favor, digite o índice do Dado para ser editado." );

        boolean foi = false;
        while ( foi == false ) {
            try {
                int num = Integer.parseInt ( msg );
                foi = true;
            }
            catch ( Exception e ) {
                foi = false;
                msg = JOptionPane.showInputDialog ( this, "O indice precisa ser um número." );
            }
        }

        Cliente.getInstance ().enviarMensagemParaServidor ( Producao.MODIFY_REQUEST, msg );

    }//GEN-LAST:event_buttEditarActionPerformed

    private void buttDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDesconectarActionPerformed
        // TODO add your handling code here:
        Cliente.getInstance ().disconectarCliente ();
        System.exit ( 0 );
    }//GEN-LAST:event_buttDesconectarActionPerformed

    private void buttProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttProcurarActionPerformed
        // TODO add your handling code here:
                String msg = JOptionPane.showInputDialog ( this, "Por favor, digite o índice do Dado para ser buscado." );

        boolean foi = false;
        while ( foi == false ) {
            try {
                int num = Integer.parseInt ( msg );
                foi = true;
            }
            catch ( Exception e ) {
                foi = false;
                msg = JOptionPane.showInputDialog ( this, "O indice precisa ser um número." );
            }
        }

        Cliente.getInstance ().enviarMensagemParaServidor (Producao.FIND_REQUEST, msg );
    }//GEN-LAST:event_buttProcurarActionPerformed

    @SuppressWarnings("null")
    private void buttDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDeletarActionPerformed
        // TODO add your handling code here:
        String msg = JOptionPane.showInputDialog ( this, "Por favor, digite o índice do Dado a ser deletado." );
        if( msg == null || (msg != null && "".equals(msg)))
            return;
        boolean foi = false;
        while ( foi == false ) {
            try {
                int num = Integer.parseInt ( msg );
                foi = true;
            }
            catch ( Exception e ) {
                foi = false;
                msg = JOptionPane.showInputDialog ( this, "O indice precisa ser um número." );
            }
        }

        Cliente.getInstance ().enviarMensagemParaServidor (Producao.EXCLUDE_REQUEST, msg );
    }//GEN-LAST:event_buttDeletarActionPerformed

    private void buttInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttInserirActionPerformed
        // TODO add your handling code here:
        Cliente.getInstance ().enviarMensagemParaServidor ( Producao.INCLUDE_REQUEST, "" );
    }//GEN-LAST:event_buttInserirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttDeletar;
    private javax.swing.JButton buttDesconectar;
    private javax.swing.JButton buttEditar;
    private javax.swing.JButton buttInserir;
    private javax.swing.JButton buttProcurar;
    private javax.swing.JLabel ipServer;
    // End of variables declaration//GEN-END:variables
}
